# Generated by Django 6.1 on 2026-08-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZFactorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.FloatField(help_text='Temperature in degrees Celsius')),
                ('pressure_psia', models.FloatField(help_text='Pressure in psia')),
                ('z_factor', models.FloatField(help_text='Compressibility factor (Z), averaged across compositions')),
                ('sample_count', models.PositiveIntegerField(default=1, help_text='Number of raw simulation rows averaged into this point')),
            ],
            options={
                'ordering': ['temperature_c', 'pressure_psia'],
                'indexes': [models.Index(fields=['temperature_c'], name='chart_zfact_tempera_fb6f9c_idx'), models.Index(fields=['pressure_psia'], name='chart_zfact_pressur_dbc6bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('temperature_c', 'pressure_psia'), name='unique_temperature_pressure_point')],
            },
        ),
    ]
