# Generated by Django 6.1 on 2026-08-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZRawDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(help_text='Original CSV file this row came from', max_length=255)),
                ('case_label', models.CharField(blank=True, help_text="Case/row label from the source file, e.g. 'Case 1042'", max_length=64, null=True)),
                ('temperature_c', models.FloatField(help_text='Temperature in degrees Celsius')),
                ('pressure_psia', models.FloatField(help_text='Pressure in psia')),
                ('z_factor', models.FloatField(help_text='Compressibility factor (Z) as reported in the source row')),
                ('h2o_mole_frac', models.FloatField(blank=True, help_text='H2O mole fraction (master composition or x_H2O)', null=True)),
                ('ch4_mole_frac', models.FloatField(blank=True, help_text='Methane mole fraction (master composition)', null=True)),
                ('co2_mole_percent', models.FloatField(blank=True, help_text='CO2 composition, mole %', null=True)),
                ('reduced_pressure', models.FloatField(blank=True, help_text='Pr, reduced pressure (CCS dataset only)', null=True)),
                ('reduced_temperature', models.FloatField(blank=True, help_text='Tr, reduced temperature (CCS dataset only)', null=True)),
                ('phase', models.CharField(blank=True, help_text='Reported phase (CCS dataset only)', max_length=32, null=True)),
                ('is_outlier', models.BooleanField(default=False, help_text='True if Z fell outside a physically plausible range (a simulator solver-glitch row), excluded from the averaged chart')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['temperature_c'], name='chart_zrawd_tempera_385eb5_idx'), models.Index(fields=['pressure_psia'], name='chart_zrawd_pressur_aafebc_idx'), models.Index(fields=['source_file'], name='chart_zrawd_source__c8318a_idx'), models.Index(fields=['is_outlier'], name='chart_zrawd_is_outl_ac94fc_idx')],
            },
        ),
    ]
